#!/usr/bin/env bash

set -euo pipefail

# Run this script from the talas_vlm_embed project root.

# datasets

wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/images_zip/ImageNet_1K.zip" -P "datasets"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/images_zip/HatefulMemes.zip" -P "datasets"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/images_zip/VOC2007.zip" -P "datasets"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/images_zip/N24News.zip" -P "datasets"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/images_zip/SUN397.zip" -P "datasets"
wget -c "https://huggingface.co/datasets/VoCuc/vlm-teacher-embedding/resolve/main/B3_Qwen2_2B_cls.tar.gz" -P "datasets"
wget -c "https://huggingface.co/datasets/VoCuc/vlm-teacher-embedding/resolve/main/B3_Qwen2_2B_vqa.tar.gz" -P "datasets"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-eval/resolve/main/images.zip" -P "datasets"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/OK-VQA/diverse_instruction-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/OK-VQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/OK-VQA/original-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/OK-VQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/OK-VQA/train-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/OK-VQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/A-OKVQA/diverse_instruction-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/A-OKVQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/A-OKVQA/original-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/A-OKVQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/A-OKVQA/train-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/A-OKVQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/DocVQA/diverse_instruction-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/DocVQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/DocVQA/original-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/DocVQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/DocVQA/train-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/DocVQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/InfographicsVQA/diverse_instruction-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/InfographicsVQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/InfographicsVQA/original-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/InfographicsVQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/InfographicsVQA/train-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/InfographicsVQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/ChartQA/diverse_instruction-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/ChartQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/ChartQA/original-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/ChartQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/ChartQA/train-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/ChartQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/Visual7W/diverse_instruction-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/Visual7W"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/Visual7W/original-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/Visual7W"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/Visual7W/train-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/Visual7W"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/ImageNet_1K/diverse_instruction-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/ImageNet_1K"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/ImageNet_1K/original-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/ImageNet_1K"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/ImageNet_1K/train-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/ImageNet_1K"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/N24News/diverse_instruction-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/N24News"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/N24News/original-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/N24News"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/N24News/train-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/N24News"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/HatefulMemes/diverse_instruction-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/HatefulMemes"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/HatefulMemes/original-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/HatefulMemes"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/HatefulMemes/train-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/HatefulMemes"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/VOC2007/diverse_instruction-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/VOC2007"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/VOC2007/original-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/VOC2007"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/VOC2007/train-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/VOC2007"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/SUN397/diverse_instruction-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/SUN397"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/SUN397/original-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/SUN397"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/SUN397/train-00000-of-00001.parquet" -P "vlm2vec_train/MMEB-train/SUN397"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-eval/resolve/main/ImageNet-1K/test-00000-of-00001.parquet" -P "vlm2vec_eval/MMEB-eval/ImageNet-1K"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-eval/resolve/main/N24News/test-00000-of-00001.parquet" -P "vlm2vec_eval/MMEB-eval/N24News"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-eval/resolve/main/HatefulMemes/test-00000-of-00001.parquet" -P "vlm2vec_eval/MMEB-eval/HatefulMemes"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-eval/resolve/main/VOC2007/test-00000-of-00001.parquet" -P "vlm2vec_eval/MMEB-eval/VOC2007"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-eval/resolve/main/SUN397/test-00000-of-00001.parquet" -P "vlm2vec_eval/MMEB-eval/SUN397"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-eval/resolve/main/Place365/test-00000-of-00001.parquet" -P "vlm2vec_eval/MMEB-eval/Place365"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-eval/resolve/main/ImageNet-A/test-00000-of-00001.parquet" -P "vlm2vec_eval/MMEB-eval/ImageNet-A"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-eval/resolve/main/ImageNet-R/test-00000-of-00001.parquet" -P "vlm2vec_eval/MMEB-eval/ImageNet-R"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-eval/resolve/main/ObjectNet/test-00000-of-00001.parquet" -P "vlm2vec_eval/MMEB-eval/ObjectNet"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-eval/resolve/main/Country211/test-00000-of-00001.parquet" -P "vlm2vec_eval/MMEB-eval/Country211"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-eval/resolve/main/OK-VQA/test-00000-of-00001.parquet" -P "vlm2vec_eval/MMEB-eval/OK-VQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-eval/resolve/main/A-OKVQA/test-00000-of-00001.parquet" -P "vlm2vec_eval/MMEB-eval/A-OKVQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-eval/resolve/main/DocVQA/test-00000-of-00001.parquet" -P "vlm2vec_eval/MMEB-eval/DocVQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-eval/resolve/main/InfographicsVQA/test-00000-of-00001.parquet" -P "vlm2vec_eval/MMEB-eval/InfographicsVQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-eval/resolve/main/ChartQA/test-00000-of-00001.parquet" -P "vlm2vec_eval/MMEB-eval/ChartQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-eval/resolve/main/Visual7W/test-00000-of-00001.parquet" -P "vlm2vec_eval/MMEB-eval/Visual7W"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-eval/resolve/main/ScienceQA/test-00000-of-00001.parquet" -P "vlm2vec_eval/MMEB-eval/ScienceQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-eval/resolve/main/VizWiz/test-00000-of-00001.parquet" -P "vlm2vec_eval/MMEB-eval/VizWiz"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-eval/resolve/main/GQA/test-00000-of-00001.parquet" -P "vlm2vec_eval/MMEB-eval/GQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-eval/resolve/main/TextVQA/test-00000-of-00001.parquet" -P "vlm2vec_eval/MMEB-eval/TextVQA"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/images_zip/A-OKVQA.zip" -P "datasets"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/images_zip/ChartQA.zip" -P "datasets"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/images_zip/DocVQA.zip" -P "datasets"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/images_zip/InfographicsVQA.zip" -P "datasets"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/images_zip/Visual7W.zip" -P "datasets"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/images_zip/OK-VQA.zip" -P "datasets"
wget -c "https://huggingface.co/datasets/TIGER-Lab/MMEB-train/resolve/main/images_zip/MSCOCO.zip" -P "datasets"
wget -c "https://huggingface.co/VoCuc/en_core_web_sm/resolve/main/en_core_web_sm.zip" -O "en_core_web_sm.zip"

wget -c "https://huggingface.co/datasets/VoCuc/vlm-teacher-embedding/resolve/main/B3_Qwen2_2B_grounding.tar.gz" -P "datasets"
wget -c "https://huggingface.co/datasets/VoCuc/vlm-teacher-embedding/resolve/main/B3_Qwen2_7B_cls.tar.gz" -P "datasets"

# models

hf download "raghavlite/B3_Qwen2_2B" --local-dir "models/B3_Qwen2_2B"
hf download "raghavlite/B3_Qwen2_7B" --local-dir "models/B3_Qwen2_7B"
hf download "apple/FastVLM-0.5B" --local-dir "models/FastVLM-0.5B"
hf download "llava-hf/llava-onevision-qwen2-0.5b-ov-hf" --local-dir "models/llava-onevision-qwen2-0.5b-ov-hf"
hf download "Qwen/Qwen2-VL-2B-Instruct" --local-dir "models/Qwen/Qwen2-VL-2B-Instruct"
