[project]
name = "talas-vlm-embed"
version = "0.1.0"
description = "VLM embedding training and evaluation scripts."
readme = "README.md"
requires-python = ">=3.11,<3.13"
license = "Apache-2.0"
dependencies = [
    "numpy==1.26.4",
    "torch==2.9.0",
    "torchvision==0.24.0",
    "transformers==4.57.3",
    "huggingface-hub",
    "peft==0.17.1",
    "accelerate==1.10.1",
    "datasets==4.1.1",
    "scipy",
    "tqdm",
    "wandb",
    "pillow",
    "wrapt",
    "py-cpuinfo",
    "hjson",
    "scikit-learn",
    "scikit-image",
    "qwen-vl-utils",
    "ray",
    "timm==0.9.12",
    "sentencepiece",
    "opencv-python",
    "decord",
    "hnswlib",
    "einops",
    "deepspeed==0.17.6",
    "numba",
    "tslearn",
    "hdbscan",
    "spacy",
    "gpustat",
    "matplotlib",
]

[tool.uv]
package = false
